// react/TODO/todo/src/components/DataList/DataList.js
import React from 'react';
import './DataList.css';
import FormButton from '../FormButton/FormButton';
import { Badge } from 'react-bootstrap';
import { Link } from 'react-router-dom';

class DataList extends React.Component {

  constructor() {
    super()
  }
  

  render() {
    return (
      <div index={this.props.index} key={this.props.index} className="dataList">
        <div index={this.props.index} className="image"><img src={this.props.image} alt={this.props.alt} width="100" height="100" index={this.props.index}/></div>
        <div className="info">
          <div className="card-number">
            <Link to={
              {
                pathname : "/data/" + this.props.index,
                state: this.props
              }
            }><Badge variant="info">Click to View Card: {this.props.index}</Badge></Link>
          </div>
          <div index={this.props.index} contentEditable="false" data-type="title" className="title card-title h5">{this.props.title}</div>
          <div index={this.props.index} contentEditable="false" data-type="desc" className="desc"><p className="card-text">{this.props.description}</p></div>
          <div className="remove" index={this.props.index}>
            <FormButton label="remove" type="button" variant="danger"></FormButton>
          </div>
          
        </div>
      </div>
    )
  }

}

DataList.propTypes = {};

DataList.defaultProps = {};

export default DataList;

// angular/todo/src/app/components/data-list/data-list.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { GetDataService } from '../../get-data.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-data-list',
  templateUrl: './data-list.component.html',
  styleUrls: ['./data-list.component.css']
})
export class DataListComponent implements OnInit {

  @Input()
  index:number;

  @Input()
  description:string;

  @Input()
  title:string;

  @Input()
  image:string;


  constructor(private getDataService : GetDataService, private router: Router) { }

  ngOnInit(): void {
  }

  navigateToData($event, index, title, description, image) {
    this.getDataService.selectData({index, title, description, image});
    this.router.navigate(["/data", index]);
  }

}

<div [id]="index"  class="dataList">
    <div [id]="index" class="image"><img [src]="image" alt="alt" width="100" height="100" [id]="index"/></div>
    <div class="info">
      <div class="card-number">
        <a (click)="navigateToData($event, index, title, description, image)" ><span class="badge badge-info">Click to View Card: {{index}}</span></a>
      </div>
      <div [id]="index" contentEditable="false" class="title card-title h5">{{title}}</div>
      <div [id]="index" contentEditable="false" class="desc"><p class="card-text">{{description}}</p></div>
      <div class="remove" [id]="index">
        <app-button btnClass="btn-danger" label="Remove"></app-button>
      </div>
      
    </div>
  </div>
