// react/TODO/todo/src/components/Data/Data.js
import React from 'react';
import './Data.css';
import { Badge } from 'react-bootstrap';
import { Link } from 'react-router-dom';

class Data extends React.Component {

  constructor() {
    super()
  }
  

  render() {
    return (
      <div index={this.props.location.state.index} key={this.props.location.state.index} className="container data">
        <div className="home">
        <Link to={
              {
                pathname : "/"
              }
            }><Badge variant="info">Click to go Home</Badge></Link>        
          </div>
        <div index={this.props.location.state.index} className="image"><img src={this.props.location.state.image} alt={this.props.location.state.alt} width="100" height="100" index={this.props.location.state.index}/></div>
        <div className="info">
            <Badge variant="info">Card: {this.props.location.state.index}</Badge>
          <div index={this.props.location.state.index} contentEditable="true" className="title card-title h5">{this.props.location.state.title}</div>
          <div index={this.props.location.state.index} contentEditable="true" className="desc"><p className="card-text">{this.props.location.state.description}</p></div>
          
        </div>
      </div>
    )
  }

}

Data.propTypes = {};

Data.defaultProps = {};

export default Data;

// angular/todo/src/app/components/data/data.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { GetDataService } from 'src/app/get-data.service';


@Component({
  selector: 'app-data',
  templateUrl: './data.component.html',
  styleUrls: ['./data.component.css']
})
export class DataComponent implements OnInit {
  
  @Input()
  index:number;

  @Input()
  description:string;

  @Input()
  title:string;

  @Input()
  image:string;


  constructor(private getDataService : GetDataService) { }

  ngOnInit(): void {
    const data = this.getDataService.selectedData;
    this.index = parseInt(data.index);
    this.description = data.description;
    this.title = data.title;
    this.image = data.image;
  }

}

<div [id]="index" class="container data">
    <a routerLink="/"><span class="badge badge-info home">Click to go Home</span></a>
    <div [id]="index" class="image"><img [src]="image" alt="alt" width="100" height="100" [id]="index"/></div>
    <div class="info">
      <div class="card-number">
        <span class="badge badge-info">Card: {{index}}</span>
      </div>
      <div [id]="index" contentEditable="true" class="title card-title h5">{{title}}</div>
      <div [id]="index" contentEditable="true" class="desc"><p class="card-text">{{description}}</p></div>
      
    </div>
  </div>
