// vue/todo/src/components/Home.vue
<template>
  <div class="container">
    <form ID="vue-form">
      <InputBox type="text" id="title" label="Title" v-on:keyup="titleTextBoxEvent($event)"/>
      <div class="tag_count">
        <InputBox type="number" id="count" label="Enter Count" v-bind:value="count" v-on:keyup="numberTextBoxEvent($event)"/>
        <InputBox type="text" id="tag" label="Search by Tag" v-bind:value="tag" v-on:keyup="tagEvent($event)"/>
      </div>
    </form>
       <div id="vue-data-list">
        <div v-for="item in dataList" :key="item.id" v-on:click="containerClicked($event)" >
          <DataList :title="item.title" :index="item.id" :key="item.id" :tag="item.tag"></DataList>
        </div>
      </div>
      <Button label="Add" type="button" variant="primary" v-on:clicked="addButtonClicked" id="vue-add-button"/>
  </div>
</template>

<script>

import InputBox from './InputBox.vue'
import Button from './Button.vue' 
import DataList from './DataList.vue' 
import Data from '../data.js';

const data = new Data();

export default {
  name: 'Home',
  components: {
    InputBox,
    Button,
    DataList
  },
  data: () => {
      return {
        title: data.title,
        count: data.count,
        tag: "",
        dataList: []
    }
  },
  methods: {
    populateList(count, currentDataList=[]) {
      const dataList = []
      for(let i=1; i<=count;i++) {
        const tag = Math.randomString()
        dataList.push({
          id : i,
          title: this.title,
          tag: tag
        })
      }
      performance.trigger();
      this.dataList = [...currentDataList, ...dataList];
    },
    addButtonClicked() {
      this.populateList(this.count, this.dataList);
    },
    numberTextBoxEvent($event) {
      this.count = parseInt($event.target.value)
      this.populateList(this.count);
    },

    titleTextBoxEvent($event) {
      this.title = $event.target.value
      this.populateList(this.count);
    },

    containerClicked($event) {
      if($event.target.type === "button") {
        const elem = $event.target.parentElement;
        const tag = (elem.getAttribute("tag"));
        performance.trigger();
        this.dataList = this.dataList.filter(data => (data.tag) !== tag);
      }
    },

    tagEvent(event) {
      if(event.target.value.length) {
        const dataList = this.dataList.filter(data => {
          return (data.tag.includes(event.target.value))
        });
        performance.trigger();
        this.dataList = dataList;
      }  else{
        this.populateList(this.count);  
      }   
        
    }
  }
}
</script>

<style>
  
  .container {
    display: grid;
  }

  .container .tag_count {
    display: flex;
    justify-content: space-between;
  }


</style>

// angular/todo/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { GetDataService } from '../../get-data.service';


@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  data: any = {}
  dataList = []
  static MAX_COUNT = 100;

  constructor(private getDataService : GetDataService) {
    this.data = getDataService.getData()
  }

  ngOnInit(): void {
  }


  populateList(count, currentDataList=[]) {
    const dataList = []
      for(let i=1; i<=count;i++) {
        const tag = Math['randomString']()
        dataList.push({
          id : i,
          title: this.data.title,
          tag: tag
        })
      }
      performance['trigger']();
      this.dataList = [...currentDataList, ...dataList];;
  }

  titleTextBoxEvent(event) {
    this.data.title = event.target.value;
    this.populateList(this.data.count);
  }

  numberTextBoxEvent(event) {
    let count = parseInt(event.target.value);
    count = (count <= HomeComponent.MAX_COUNT) ? count : HomeComponent.MAX_COUNT;
    this.data.count = count;
    this.populateList(this.data.count);
  }

  addButtonClicked(event) {
    this.populateList(this.data.count, this.dataList);
  }


  containerClicked(event) {
    if(event.target.type === "button") {
      const elem = event.target.parentElement.parentElement;
      const tag = (elem.getAttribute("id"));
      performance['trigger']();
      this.dataList = this.dataList.filter(data => (data.tag) !== tag);
    }
  }

  tagEvent(event) {
    if(event.target.value.length) {
      const dataList = this.dataList.filter(data => {
        return (data.tag.includes(event.target.value))
      });
      performance['trigger']();
      this.dataList = dataList;
    }  else{
      this.populateList(this.data.count);  
    }   
      
  }

}


<div class="container">
    <form id="angular-form">
      <app-input-box type="text"  id = "title" label="Title" (onKeyUpEmitter)="titleTextBoxEvent($event)"></app-input-box>
      <br/>
      <div class="tag_count">
          <app-input-box type="number"  label="Enter Count" max="100" (onKeyUpEmitter)="numberTextBoxEvent($event)"></app-input-box>
          <app-input-box type="text"  label="Search by Tag" max="100" (onKeyUpEmitter)="tagEvent($event)"></app-input-box>
      </div>
    </form>
      <br/>
      <div id="angular-data-list">
        <div *ngFor="let item of dataList" (click)="containerClicked($event)" >
          <app-data-list title="{{item.title}}" index="{{item.id}}" tag="{{item.tag}}" ></app-data-list>
        </div>
      </div>
      <app-button btnClass="btn-primary" label="Add" (onClickEmitter)="addButtonClicked($event)" id="angular-add-button"></app-button>
    
    
    
  </div>
