// vue/todo/src/components/Data.vue

<template>
     <div :index="index" :key="index" class="container data">
        <div class="home"  @click="routeToCardList()">
              <b-badge variant="info">Click to go Home</b-badge>
        </div>
        <div :index="index" class="image"><img :src="image" alt="alt" width="100" height="100" :index="index"/></div>
        <div class="info" :index="index">
          <div>
              <b-badge variant="info">Card: {{index}}</b-badge>
          </div>
          <div :index="index" contentEditable="true" class="title card-title h5">{{title}}</div>
          <div :index="index" contentEditable="true" class="desc"><p class="card-text">{{description}}</p></div>

          
        </div>
      </div>
</template>

<script>

export default {
  name: 'Data',
  data() {
      return {
        index: "",
        title: '',
        description: '',
        image: ''
    }
  },
  methods: {
    routeToCardList() {
      this.$router.push({
        name : "DataList"
      })
    }
  },
  created() {
      this.image = this.$route.params.image,
      this.description = this.$route.params.description,
      this.title = this.$route.params.title,
      this.index = this.$route.params.index
  }
}
</script>

<style>
    .data {
        border: 1px solid rgba(0,0,0,.125);
        border-radius: .25rem;
        margin-bottom: 15px;
    }

    .data .home {
        cursor: pointer;
        grid-row-start: 1;
        grid-row-end: 1;
    }

    .data .image {
        grid-row-start: 2;
        grid-row-end: 2;
    }

    .data .info {
        display: flex;
        flex-direction: column;
        grid-row-start: 3;
        grid-row-end: 3;
        padding: 10px;;
    }

    .data .info .desc {
        flex-grow: 1;
    }

    .data .info .remove {
        align-self: flex-end;
    }


    .data .image img {
        width: 100%;
        height: 100%;
    }

</style>

// react/TODO/todo/src/components/Data/Data.js
import React from 'react';
import './Data.css';
import { Badge } from 'react-bootstrap';
import { Link } from 'react-router-dom';

class Data extends React.Component {

  constructor() {
    super()
  }
  

  render() {
    return (
      <div index={this.props.location.state.index} key={this.props.location.state.index} className="container data">
        <div className="home">
        <Link to={
              {
                pathname : "/"
              }
            }><Badge variant="info">Click to go Home</Badge></Link>        
          </div>
        <div index={this.props.location.state.index} className="image"><img src={this.props.location.state.image} alt={this.props.location.state.alt} width="100" height="100" index={this.props.location.state.index}/></div>
        <div className="info">
            <Badge variant="info">Card: {this.props.location.state.index}</Badge>
          <div index={this.props.location.state.index} contentEditable="true" className="title card-title h5">{this.props.location.state.title}</div>
          <div index={this.props.location.state.index} contentEditable="true" className="desc"><p className="card-text">{this.props.location.state.description}</p></div>
          
        </div>
      </div>
    )
  }

}

Data.propTypes = {};

Data.defaultProps = {};

export default Data;
